export const INITIALIZING = ' INITIALIZING'
export const INITIALIZE = ' INITIALIZE'
export const RECIEVE_ITEMS = 'RECIEVE_ITEMS'
export const FETCHING_ITEMS = 'FETCHING_ITEMS'
export const CLEAR_ITEMS = 'CLEAR_ITEMS'

export const ADD_KEYWORD = 'ADD_KEYWORD'
export const SELECT_KEYWORD = 'SELECT_KEYWORD'
export const CHANGE_BOOKMARK_FILTER = 'CHANGE_BOOKMARK_FILTER'

